### ISSUE TITLE
博客搭建 | ayuan的博客

### ISSUE THREAD

**Issue by ayuan519** [ayuan519/blogComment#6]
https://ayuan519.github.io/2019/11/14/buildingBlog/ 

 主要记录自己在搭建博客时遇到的问题及过程，持续更新。

**Comment by leleniu** [comment]
![avatar](https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=1382454344,4288405557&fm=173&app=25&f=JPEG?w=550&h=305&s=F2202EE756131BD04203A1330300D05B)

**Comment by Beamon-project** [comment]
![avatar](https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=1382454344,4288405557&fm=173&app=25&f=JPEG?w=550&h=305&s=F2202EE756131BD04203A1330300D05B)

**Comment by leleniu** [comment]
![avatar](https://ss1.baidu.com/6ONXsjip0QIZ8tyhnq/it/u=3686996278,2126441785&fm=173&app=25&f=JPEG?w=640&h=384&s=B70AB7E39FB385C800C07B2E0300A054)
